# Generated by Django 5.1 on 2024-09-12 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_test_remove_answer_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.document'),
        ),
    ]
